build:
  image: golang:1.5
  commands:
    - make deps
    - make build
    - make test

publish:
  docker:
    username: jackspirou
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: jackspirou/drone-github-release
    when:
      branch: master

plugin:
  name: GitHub Release
  desc: Publishs files and artifacts to GitHub Releases
  type: publish
  image: jackspirou/drone-github-release
  labels:
    - github
    - release
