workspace:
  base: /go
  path: src/github.com/JonasFranzDEV/drone-gitea-release

pipeline:
  test:
    image: golang:1.9
    pull: true
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out

  build_linux_amd64:
    image: golang:1.9
    pull: true
    group: build
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/amd64/drone-gitea-release

  build_linux_arm64:
    image: golang:1.9
    pull: true
    group: build
    environment:
      - GOOS=linux
      - GOARCH=arm64
      - CGO_ENABLED=0
    commands:
      - go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/arm64/drone-gitea-release

  build_linux_arm:
    image: golang:1.9
    pull: true
    group: build
    environment:
      - GOOS=linux
      - GOARCH=arm
      - CGO_ENABLED=0
      - GOARM=7
    commands:
      - go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/arm/drone-gitea-release

  # build_windows_amd64:
  #   image: golang:1.9-nanoserver
  #   pull: true
  #   group: build
  #   environment:
  #     - GOOS=windows
  #     - GOARCH=amd64
  #     - CGO_ENABLED=0
  #   commands:
  #     - go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/windows/amd64/drone-gitea-release